CHEZMOI: improve bat update

diff --git a/.chezmoitemplates/bat.tmpl b/.chezmoitemplates/bat.tmpl
--- a/.chezmoitemplates/bat.tmpl
+++ b/.chezmoitemplates/bat.tmpl
@@ -5,6 +5,6 @@ vim:ft=bash.gotexttmpl
 {{ template "path.tmpl" . }}
 
 {{ if lookPath "bat" }}
-	echo "bat. Update bat cache"
-	bat cache --build
+	echo "bat. Update bat Cache"
+	bat cache --build || (echo "Rebuild bat Cache Procedure Failed" && exit 1)
 {{ end }}
