BREW: force relink python

diff --git a/.chezmoitemplates/darwin.tmpl b/.chezmoitemplates/darwin.tmpl
--- a/.chezmoitemplates/darwin.tmpl
+++ b/.chezmoitemplates/darwin.tmpl
@@ -7,5 +7,7 @@ vim:ft=bash.gotexttmpl
 echo "Darwin. Update brew packages"
 export HOMEBREW_CASK_OPTS="--appdir={{ (joinPath .chezmoi.homeDir "Applications") }} --no-quarantine"
 brew analytics off || exit 0
-(brew update && brew upgrade && brew upgrade --cask) || exit 1
-(brew cleanup --quiet --prune=120 && brew autoremove) || exit 1
+(brew update && brew upgrade && brew upgrade --cask) || (echo "Brew Update and Upgrade Procedure Failed" && exit 1)
+brew unlink --quiet gettext; brew link --force gettext
+(brew link --overwrite python) || (echo "Brew Python Link Procedure Failed" && exit 1)
+(brew cleanup --quiet --prune=120 && brew autoremove) || (echo "Brew Cleanup Procedure Fasiled" && exit 1)
