CHEZMOI: improve font cache update

diff --git a/.chezmoitemplates/update-fonts-cache.tmpl b/.chezmoitemplates/update-fonts-cache.tmpl
--- a/.chezmoitemplates/update-fonts-cache.tmpl
+++ b/.chezmoitemplates/update-fonts-cache.tmpl
@@ -5,6 +5,6 @@ vim:ft=bash.gotexttmpl
 {{ template "path.tmpl" . }}
 
 {{ if eq .chezmoi.os "linux" }}
-echo "Linux. Update fonts cache"
-fc-cache -f -v
+echo "Linux. Update Fonts Cache"
+fc-cache -f -v || (echo "Fonts Cache Build Failed" && exit 1)
 {{ end }}
